# Generated by Django 4.2.7 on 2024-03-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_follow_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='follow_request',
            new_name='following',
        ),
    ]
