# Generated by Django 4.2.7 on 2024-03-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_block_deleted_at_remove_reaction_emoji_and_more'),
        ('notifications', '0003_rename_follow_request_notification_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='peck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.peck'),
        ),
    ]
