# Generated by Django 4.2.7 on 2024-02-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_follow_request_and_more'),
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
    ]
