# Generated by Django 4.2.7 on 2024-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20240221_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notified_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task', 'for task'), ('reaction', 'for reaction'), ('follow', 'for follow'), ('follow_request', 'for follow request'), ('follow_request_accepted', 'for follow request accpeted'), ('pecked', 'for pecked'), ('trending_up', 'for trending up'), ('trending_down', 'for trending down')], max_length=128),
        ),
        migrations.AlterField(
            model_name='taskreminder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
