# Generated by Django 4.2.11 on 2024-05-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_block_blockee_alter_block_blocker'),
        ('notifications', '0008_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.comment'),
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='fail_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_reminder', 'for task reminder'), ('reaction', 'for reaction'), ('follow', 'for follow'), ('follow_request', 'for follow request'), ('follow_request_accepted', 'for follow request accpeted'), ('peck', 'for peck'), ('comment', 'for comment'), ('trending_up', 'for trending up'), ('trending_down', 'for trending down')], max_length=128),
        ),
    ]
