# Generated by Django 4.2.11 on 2024-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_comment_webpushsubscription_fail_cnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_reminder', 'for task reminder'), ('reaction', 'for reaction'), ('follow', 'for follow'), ('follow_request', 'for follow request'), ('follow_request_accepted', 'for follow request accpeted'), ('peck', 'for peck'), ('comment', 'for comment')], max_length=128),
        ),
    ]
