# Generated by Django 4.2.11 on 2024-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreminder',
            name='delta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
