# Generated by Django 4.2.11 on 2024-07-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_taskreminder_delta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='taskreminder',
            table='task_reminders',
        ),
        migrations.AlterModelTable(
            name='webpushsubscription',
            table='web_push_subscriptions',
        ),
    ]
