# Generated by Django 4.2.14 on 2024-07-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_webpushsubscription_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpushsubscription',
            name='device',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
    ]
