# Generated by Django 4.2.14 on 2024-07-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_notification_table_alter_taskreminder_table_and_more'),
        ('notifications', '0013_webpushsubscription_device'),
    ]

    operations = [
    ]
