# Generated by Django 4.2.18 on 2025-02-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_merge_20240730_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpushsubscription',
            name='excluded_types',
            field=models.JSONField(default=list),
        ),
    ]
