# Generated by Django 4.2.23 on 2025-07-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_webpushsubscription_excluded_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebPushSubscription',
        ),
    ]
