# Generated by Django 4.2.23 on 2025-08-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_taskreaction_and_more'),
        ('notifications', '0017_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.taskreaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_reminder', 'for task reminder'), ('reaction', 'for reaction'), ('task_reaction', 'for task reaction'), ('follow', 'for follow'), ('follow_request', 'for follow request'), ('follow_request_accepted', 'for follow request accpeted'), ('peck', 'for peck'), ('comment', 'for comment')], max_length=128),
        ),
    ]
