# Generated by Django 4.2.23 on 2025-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_notification_task_reaction_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reaction',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_reminder', 'for task reminder'), ('task_reaction', 'for task reaction'), ('follow', 'for follow'), ('follow_request', 'for follow request'), ('follow_request_accepted', 'for follow request accpeted'), ('peck', 'for peck'), ('comment', 'for comment')], max_length=128),
        ),
    ]
