# Generated by Django 4.2.25 on 2025-10-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_remove_notification_comment_remove_notification_peck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.URLField(max_length=1024),
        ),
    ]
