version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react"
        versions: 
          - ">=19.0.0"
      - dependency-name: "react-dom"
        versions: 
          - ">=19.0.0"
      - dependency-name: "@types/react"
        versions: 
          - ">=19.0.0"
      - dependency-name: "@types/react-dom"
        versions: 
          - ">=19.0.0"
      - dependency-name: "react-router-dom"
        versions: 
          - ">=7.0.0"
    groups:
      npm-minor-patch:
        applies-to: version-updates 
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      pip-minor-patch:
        applies-to: version-updates 
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "django"
        versions: 
          - ">=5.0.0"
      - dependency-name: "django-stubs*"
        versions: 
          - ">=5.0.0"
  - package-ecosystem: "docker"
    directories:
      - "/frontend"
      - "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
