skip-missing: true
ignores:
    # dependencies
    - pnpm
    # devDependencies
    - \@tanstack/react-query-devtools
    - \@trivago/prettier-plugin-sort-imports
    - \@types/react
    - \@types/react-dom
    - eslint
    - prettier
    - typescript
