# https://docs.docker.com/compose/compose-file/

name: peak

services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - django_admin_static:/usr/share/caddy/django_static
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/health/ok"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./backend/:/usr/src/backend/
      - django_admin_static:/backend/static
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.dev
  db: 
    image: postgres:16.2-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "peakuser", "-d", "peakdb"] 
      # https://github.com/peter-evans/docker-compose-healthcheck/issues/16#issuecomment-1039718816
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: peakuser
      POSTGRES_PASSWORD: PEAK_DEFAULT_PASSWORD
      POSTGRES_DB: peakdb
volumes:
  django_admin_static:
  db_data:
  caddy_data:
    external: true
  caddy_config: