# Generated by Django 4.2.7 on 2024-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('goal', 'Goal')]),
        ),
    ]
