# Generated by Django 4.2.11 on 2024-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('regular', 'Regular'), ('goal', 'Goal')], max_length=128),
        ),
    ]
