# Generated by Django 4.2.7 on 2024-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
