# Generated by Django 4.2.7 on 2024-02-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_type'),
        ('projects', '0003_alter_project_name_alter_project_type'),
    ]

    operations = [
    ]
