# Generated by Django 4.2.14 on 2024-08-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_color'),
        ('projects', '0004_project_privacy'),
    ]

    operations = [
    ]
