# Generated by Django 4.2.14 on 2024-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_0004_alter_project_color_0004_project_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=128),
        ),
    ]
