# Generated by Django 4.2.23 on 2025-08-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='constraint_project_name',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'user'), name='constraint_project_name_active'),
        ),
    ]
