# Generated by Django 4.2.23 on 2025-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_constraint_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
