# Generated by Django 4.2.23 on 2025-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='constraint_project_name_active',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='constraint_project_name_active'),
        ),
    ]
