# Generated by Django 4.2.24 on 2025-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_constraint_project_name_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='privacy',
            field=models.CharField(choices=[('public', 'for public'), ('protected', 'for protected'), ('private', 'for private')], default='public', max_length=128),
        ),
    ]
