# Generated by Django 4.2.7 on 2024-03-30 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0003_alter_block_deleted_at_remove_reaction_emoji_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('follow_request_approval_manually', models.BooleanField(default=False)),
                ('follow_request_approval_for_followings', models.BooleanField(default=True)),
                ('follow_list_privacy', models.CharField(choices=[('public', 'for public'), ('protected', 'for protected'), ('private', 'for private')], max_length=128)),
                ('dislikable_emojis', models.ManyToManyField(related_name='dislikables', to='social.emoji')),
                ('favorite_emojis', models.ManyToManyField(related_name='favorites', to='social.emoji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
