# Generated by Django 4.2.11 on 2024-07-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting', '0002_alter_usersetting_dislikable_emojis_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersetting',
            table='user_settings',
        ),
    ]
