# Generated by Django 4.2.7 on 2024-02-19 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('order', models.IntegerField()),
                ('privacy', models.CharField()),
                ('uncompleted_task_count', models.IntegerField()),
                ('completed_task_count', models.IntegerField()),
            ],
        ),
    ]
