# Generated by Django 4.2.7 on 2024-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawer',
            name='completed_task_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='uncompleted_task_count',
            field=models.IntegerField(default=0),
        ),
    ]
