# Generated by Django 4.2.7 on 2024-02-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('drawers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
