# Generated by Django 4.2.7 on 2024-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawer',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='privacy',
            field=models.CharField(max_length=128),
        ),
    ]
