# Generated by Django 4.2.7 on 2024-03-11 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_deleted_at_alter_project_type'),
        ('drawers', '0002_alter_drawer_deleted_at_alter_drawer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawer',
            name='user',
            field=models.ForeignKey(default='2652579d-a66f-4df5-b1ab-7629860b0f7d', on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drawer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='projects.project'),
        ),
    ]
