# Generated by Django 4.2.7 on 2024-03-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0002_alter_drawer_deleted_at_alter_drawer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
