# Generated by Django 4.2.7 on 2024-03-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0002_alter_drawer_completed_task_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawer',
            name='privacy',
            field=models.CharField(choices=[('public', 'for public'), ('protected', 'for protected'), ('private', 'for private')], max_length=128),
        ),
    ]
