# Generated by Django 4.2.7 on 2024-03-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0003_alter_drawer_deleted_at'),
        ('drawers', '0003_drawer_user_alter_drawer_project'),
    ]

    operations = [
    ]
