# Generated by Django 4.2.11 on 2024-07-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0003_alter_drawer_privacy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drawer',
            table='drawers',
        ),
    ]
