# Generated by Django 4.2.18 on 2025-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0004_alter_drawer_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drawer',
            constraint=models.UniqueConstraint(fields=('name', 'project', 'user'), name='constraint_drawer_name'),
        ),
    ]
