# Generated by Django 4.2.23 on 2025-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0005_drawer_constraint_drawer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
