# Generated by Django 4.2.7 on 2024-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeat',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
