# Generated by Django 4.2.7 on 2024-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_repeat_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
