# Generated by Django 4.2.7 on 2024-02-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='privacy',
            field=models.CharField(max_length=128),
        ),
    ]
