# Generated by Django 4.2.7 on 2024-03-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date_alter_task_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='privacy',
            field=models.CharField(choices=[('public', 'for public'), ('protected', 'for protected'), ('private', 'for private')], max_length=128),
        ),
    ]
