# Generated by Django 4.2.11 on 2024-04-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_reminder_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
