# Generated by Django 4.2.11 on 2024-05-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_user'),
        ('tasks', '0007_task_assigned_at'),
    ]

    operations = [
    ]
