# Generated by Django 4.2.11 on 2024-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_merge_0007_alter_task_user_0007_task_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_tz',
            field=models.CharField(default='UTC', max_length=128),
            preserve_default=False,
        ),
    ]
