# Generated by Django 4.2.11 on 2024-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_due_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_tz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
