# Generated by Django 4.2.14 on 2024-07-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0003_alter_drawer_privacy'),
        ('tasks', '0009_task_due_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='drawers.drawer'),
        ),
    ]
