# Generated by Django 4.2.14 on 2024-07-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_drawer'),
        ('tasks', '0011_alter_repeat_table_alter_task_table'),
    ]

    operations = [
    ]
