# Generated by Django 4.2.14 on 2024-10-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_due_time_remove_task_due_tz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
