# Generated by Django 4.2.18 on 2025-02-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_due_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='repeat',
        ),
        migrations.DeleteModel(
            name='Repeat',
        ),
    ]
