# Generated by Django 4.2.24 on 2025-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_task_repeat_delete_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='privacy',
            field=models.CharField(blank=True, choices=[('public', 'for public'), ('protected', 'for protected'), ('private', 'for private')], max_length=128, null=True),
        ),
    ]
