# Generated by Django 4.2.24 on 2025-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_task_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='privacy',
            field=models.CharField(choices=[('public', 'for public'), ('protected', 'for protected'), ('private', 'for private')], default='public', max_length=128),
        ),
    ]
