const palettes = [
[
    {color: "FF6E6E", display: "핑크"},
    {color: "DC2E2E", display: "빨강"},
    {color: "8C1C1C", display: "진빨강"},
    {color: "FF6E6E", display: "핑크"},
    {color: "DC2E2E", display: "빨강"},
    {color: "8C1C1C", display: "진빨강"},
    {color: "FF6E6E", display: "핑크"},
    {color: "DC2E2E", display: "빨강"},
    {color: "8C1C1C", display: "진빨강"},
    {color: "FF6E6E", display: "핑크"},
    {color: "DC2E2E", display: "빨강"},
    {color: "8C1C1C", display: "진빨강"},
    {color: "FF6E6E", display: "핑크"},
    {color: "DC2E2E", display: "빨강"},
    {color: "8C1C1C", display: "진빨강"},
    {color: "8C1C1C", display: "진빨강"},
],
[
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
    {color: "81A6FF", display: "하늘"},
]
]

export default palettes