export const palettes = {
    theme1: [
        "red",
        "red_orange",
        "orange",
        "yellow",
        "bright_sky_blue",
        "blue",
        "magenta",
        "violet",
        "pink",
        "hot_pink",
        "light_green",
        "mint",
        "deep_purple",
        "dark_violet",
        "deep_blue",
        "deep_indigo",
    ],
    theme2: [
        "pale_pink",
        "light_coral",
        "light_cream",
        "pale_yellow",
        "sky_blue",
        "soft_blue",
        "light_lilac",
        "lavender_purple",
        "light_pink",
        "pink_pearl",
        "light_mint",
        "bright_aqua",
        "pale_violet",
        "light_purple",
        "light_blue",
        "cobalt_blue",
    ],
}

const light = {
    grey: "#CCCCCC",
    red: "#FF3B3B",
    red_orange: "#F05A29",
    orange: "#FF8D1B",
    yellow: "#FFEE00",
    bright_sky_blue: "#1CBFFF",
    blue: "#0787FF",
    magenta: "#F36FFF",
    violet: "#CE3AFF",
    pink: "#FF79C1",
    hot_pink: "#FF19C6",
    light_green: "#73FF88",
    mint: "#0FFFAF",
    deep_purple: "#7835FF",
    dark_violet: "#4C00D9",
    deep_blue: "#123EFF",
    deep_indigo: "#0C0CB2",
    pale_pink: "#FFCCD1",  
    light_coral: "#FFBAB4",  
    light_cream: "#FFDEC2",  
    pale_yellow: "#FFFBC0",  
    sky_blue: "#8EECF5",  
    soft_blue: "#7BDEFF",  
    light_lilac: "#EDE1F8",  
    lavender_purple: "#D6C2EB",  
    light_pink: "#FFBBEB",  
    pink_pearl: "#FF97C3",  
    light_mint: "#BDFFD7",  
    bright_aqua: "#93FFE8",  
    pale_violet: "#C2A0FF",  
    light_purple: "#AA84EF",  
    light_blue: "#9EDDFF",  
    cobalt_blue: "#6A9CFD",
}

const dark = {
    grey: "#858585",
    red: "#FF3B3B",
    red_orange: "#F05A29",
    orange: "#FF8D1B",
    yellow: "#FFEE00",
    bright_sky_blue: "#1CBFFF",
    blue: "#0787FF",
    magenta: "#F36FFF",
    violet: "#CE3AFF",
    pink: "#FF79C1",
    hot_pink: "#FF19C6",
    light_green: "#73FF88",
    mint: "#0FFFAF",
    deep_purple: "#7835FF",
    dark_violet: "#4C00D9",
    deep_blue: "#123EFF",
    deep_indigo: "#0C0CB2",
    pale_pink: "#FFCCD1",  
    light_coral: "#FFBAB4",  
    light_cream: "#FFDEC2",  
    pale_yellow: "#FFFBC0",  
    sky_blue: "#8EECF5",  
    soft_blue: "#7BDEFF",  
    light_lilac: "#EDE1F8",  
    lavender_purple: "#D6C2EB",  
    light_pink: "#FFBBEB",  
    pink_pearl: "#FF97C3",  
    light_mint: "#BDFFD7",  
    bright_aqua: "#93FFE8",  
    pale_violet: "#C2A0FF",  
    light_purple: "#AA84EF",  
    light_blue: "#9EDDFF",  
    cobalt_blue: "#6A9CFD",
}

const themes = {
    light: light,
    dark: dark,
}

export const getProjectColor = (theme, color) => {
    return themes[theme][color]
}
