# Generated by Django 4.2.15 on 2024-09-24 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('content_raw', models.TextField()),
                ('content', models.TextField(editable=False)),
                ('lang', models.CharField(choices=[('en', 'English'), ('ko', 'Korean')], max_length=128)),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_hearts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements_hearts',
            },
        ),
        migrations.AddConstraint(
            model_name='heart',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='constraint_announcement_user'),
        ),
    ]
