# Generated by Django 4.2.7 on 2024-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_block_deleted_at_alter_comment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='parent_type',
            field=models.CharField(max_length=128),
        ),
    ]
