# Generated by Django 4.2.7 on 2024-03-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_reaction_daily_comment_alter_reaction_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='emoji',
        ),
        migrations.AddField(
            model_name='reaction',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='social.emoji'),
        ),
    ]
