# Generated by Django 4.2.7 on 2024-02-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_reaction_daily_comment_and_more'),
        ('social', '0003_alter_emoji_name_alter_reaction_parent_type'),
    ]

    operations = [
    ]
