# Generated by Django 4.2.11 on 2024-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_block_blockee_alter_block_blocker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='is_request',
        ),
        migrations.AddField(
            model_name='following',
            name='status',
            field=models.CharField(choices=[('requested', 'request by follower'), ('accepted', 'accepted by followee'), ('rejected', 'rejected by followee'), ('canceled', 'canceled by follower')], default='requested'),
            preserve_default=False,
        ),
    ]
