# Generated by Django 4.2.11 on 2024-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_remove_following_is_request_following_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycomment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
