# Generated by Django 4.2.11 on 2024-07-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_dailycomment_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='blocks',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='dailycomment',
            table='daily_comments',
        ),
        migrations.AlterModelTable(
            name='emoji',
            table='emojis',
        ),
        migrations.AlterModelTable(
            name='following',
            table='followings',
        ),
        migrations.AlterModelTable(
            name='peck',
            table='pecks',
        ),
        migrations.AlterModelTable(
            name='reaction',
            table='reactions',
        ),
    ]
