# Generated by Django 4.2.14 on 2024-08-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_merge_20240731_0149'),
        ('social', '0008_alter_block_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='daily_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.dailycomment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_type',
            field=models.CharField(choices=[('task', 'For task'), ('daily_comment', 'For daily comment')], default='task', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
