# Generated by Django 4.2.14 on 2024-08-07 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_rename_comment_dailycomment_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyComment',
            new_name='Quote',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='daily_comment',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='daily_comment',
            new_name='quote',
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_type',
            field=models.CharField(choices=[('task', 'For task'), ('quote', 'For quote')], max_length=128),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='parent_type',
            field=models.CharField(choices=[('task', 'For task'), ('quote', 'For quote')], max_length=128),
        ),
        migrations.AlterModelTable(
            name='quote',
            table='quotes',
        ),
    ]
