# Generated by Django 4.2.15 on 2024-08-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_emoji_img_uri_emoji_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.emoji'),
        ),
    ]
