# Generated by Django 4.2.23 on 2025-08-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_remove_notification_reaction_alter_notification_type'),
        ('social', '0015_taskreaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
