# Generated by Django 4.2.24 on 2025-09-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_delete_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peck',
            name='task',
        ),
        migrations.RemoveField(
            model_name='peck',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Peck',
        ),
    ]
