# Generated by Django 4.2.24 on 2025-09-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_remove_peck_task_remove_peck_user_delete_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
