# Generated by Django 4.2.16 on 2024-12-17 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peak_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('try_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_factor_auth_tokens',
            },
        ),
        migrations.CreateModel(
            name='TOTPSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_secret', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'totp_secrets',
            },
        ),
        migrations.AddConstraint(
            model_name='twofactorauthtoken',
            constraint=models.UniqueConstraint(fields=('user',), name='constraint_user'),
        ),
    ]
