# Generated by Django 4.2.7 on 2024-02-19 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=18, unique=True)),
                ('display_name', models.CharField(max_length=18)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('followings_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('profile_img_uri', models.URLField()),
                ('bio', models.TextField(max_length=50)),
            ],
        ),
    ]
