# Generated by Django 4.2.7 on 2024-03-11 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=18, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=18)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('followings_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('profile_img_uri', models.URLField()),
                ('bio', models.TextField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
