# Generated by Django 4.2.7 on 2024-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_bio_alter_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_imgs/'),
        ),
    ]
