# Generated by Django 4.2.7 on 2024-04-02 16:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img_uri',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path),
        ),
    ]
