# Generated by Django 4.2.11 on 2024-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_profile_img_uri_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_color',
            field=models.CharField(default='c4c4c4', max_length=6),
        ),
    ]
