# Generated by Django 4.2.14 on 2024-08-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_emailverificationtoken_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordrecoverytoken',
            name='locale',
        ),
    ]
