# Generated by Django 4.2.14 on 2024-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_passwordrecoverytoken_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_color',
            field=models.CharField(max_length=128),
        ),
    ]
