# Generated by Django 4.2.14 on 2024-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_passwordrecoverytoken_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecoverytoken',
            name='locale',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
