name: Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          src: "./backend"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./backend"
  makemigrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend
      - name: Copy .env
        run: cp .env.example .env
      - name: Check makemigrations
        run: python manage.py makemigrations --check
        working-directory: ./backend
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: >-
        docker build
        --file ./backend/Dockerfile
        --tag peak-api:$(date +%s) ./backend
