name: Caddy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Caddy from Github Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release -R caddyserver/caddy download --pattern 'caddy_*_linux_amd64.tar.gz' -O - | sudo tar -xz caddy
          chmod +x caddy
      - name: Run caddy fmt for dev
        run: ./caddy fmt --config ./web/caddy.dev/Caddyfile > /dev/null
      - name: Run caddy fmt for prod
        run: ./caddy fmt --config ./web/caddy.prod/Caddyfile > /dev/null
