name: Caddy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        caddyfile: [Caddyfile, Caddyfile.prod]
    steps:
      - name: Install Caddy from Github Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release -R caddyserver/caddy download --pattern 'caddy_*_linux_amd64.tar.gz' -O - | sudo tar -xz caddy
          chmod +x caddy
      - name: Run caddy fmt
        run: caddy fmt --config ./web/${{ matrix.caddyfile }} > /dev/null
