name: Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install modules
        run: pnpm i
        working-directory: ./frontend
      - name: Run Prettier Check
        run: pnpm format:check
        working-directory: ./frontend
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install modules
        run: pnpm i
        working-directory: ./frontend
      - name: Run ESLint
        run: pnpm lint
        working-directory: ./frontend
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run depcheck
        working-directory: ./frontend
        run: npx depcheck
