name: Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install modules
        run: pnpm i
        working-directory: ./frontend
      - name: Run Prettier Check and Show Diff
        run: >-
          pnpm format:check 
          || (
            echo;
            pnpm prettier --version;
            pnpm format:write>/dev/null;
            git diff --exit-code;
          )
        working-directory: ./frontend
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install modules
        run: pnpm i
        working-directory: ./frontend
      - name: Run ESLint
        run: pnpm lint
        working-directory: ./frontend
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install modules
        run: pnpm i
        working-directory: ./frontend
      - name: Run type check
        run: pnpm type:check
        working-directory: ./frontend
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: '**/.github/workflows/*.yaml'
      - name: Run depcheck
        working-directory: ./frontend
        run: npx depcheck
  locales:
    strategy:
      matrix:
        file: [docs, home, intro, settings, translation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: '**/.github/workflows/*.yaml'
      - name: Compare keys of ${{ matrix.file }}.json
        working-directory: ./frontend/src/assets/locales
        run: npx json-diff -k ./ko/${{ matrix.file }}.json ./en/${{ matrix.file }}.json
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build the frontend Docker image 
        run: >-
          docker build
          -f ./frontend/Dockerfile
          --build-arg "BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S%z')"
          -t frontend-build ./frontend
      - name: Build frontend using the frontend image
        run: >-
          docker run
          -v ./build:/frontend/dist
          -v ./.env.example:/.env:ro
          -t frontend-build
